# Configuration for running connectors locally in bundle with connector-runtime
server:
  port: 9898

# comment out to enable inbound connectors
camunda:
  connector:
    polling:
      enabled: false


# uncomment to enable inbound connectors
#operate:
#  client:
#    enabled: true
#
#camunda:
#  operate:
#    client:
#      url: http://localhost:8081
#      username: demo
#      password: demo

zeebe:
  client:
    job:
      timeout: 15m
